[2023-12-15T17:51:15.468+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T17:51:15.475+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T17:51:15.476+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-15T17:51:15.487+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): update_transaction_fact> on 2023-12-14 00:00:00+00:00
[2023-12-15T17:51:15.494+0000] {standard_task_runner.py:57} INFO - Started process 277 to run task
[2023-12-15T17:51:15.496+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_transaction_fact', 'update_transaction_fact', 'scheduled__2023-12-14T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/transaction_fact.py', '--cfg-path', '/tmp/tmpuxt9epwx']
[2023-12-15T17:51:15.497+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask update_transaction_fact
[2023-12-15T17:51:15.537+0000] {task_command.py:416} INFO - Running <TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [running]> on host 5f9e80443a11
[2023-12-15T17:51:15.591+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_transaction_fact' AIRFLOW_CTX_TASK_ID='update_transaction_fact' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-14T00:00:00+00:00'
[2023-12-15T17:51:15.592+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: update_transaction_fact() missing 1 required positional argument: 'records'
[2023-12-15T17:51:15.600+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_transaction_fact, task_id=update_transaction_fact, execution_date=20231214T000000, start_date=20231215T175115, end_date=20231215T175115
[2023-12-15T17:51:15.608+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task update_transaction_fact (update_transaction_fact() missing 1 required positional argument: 'records'; 277)
[2023-12-15T17:51:15.628+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-15T17:51:15.644+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-15T17:57:40.161+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T17:57:40.168+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T17:57:40.168+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-15T17:57:40.176+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): update_transaction_fact> on 2023-12-14 00:00:00+00:00
[2023-12-15T17:57:40.180+0000] {standard_task_runner.py:57} INFO - Started process 89 to run task
[2023-12-15T17:57:40.182+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_transaction_fact', 'update_transaction_fact', 'scheduled__2023-12-14T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/transaction_fact.py', '--cfg-path', '/tmp/tmpmym6qfvx']
[2023-12-15T17:57:40.184+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask update_transaction_fact
[2023-12-15T17:57:40.219+0000] {task_command.py:416} INFO - Running <TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [running]> on host 1cc014cbc037
[2023-12-15T17:57:40.274+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_transaction_fact' AIRFLOW_CTX_TASK_ID='update_transaction_fact' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-14T00:00:00+00:00'
[2023-12-15T17:57:40.275+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: update_transaction_fact() missing 1 required positional argument: 'records'
[2023-12-15T17:57:40.282+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_transaction_fact, task_id=update_transaction_fact, execution_date=20231214T000000, start_date=20231215T175740, end_date=20231215T175740
[2023-12-15T17:57:40.290+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task update_transaction_fact (update_transaction_fact() missing 1 required positional argument: 'records'; 89)
[2023-12-15T17:57:40.314+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-15T17:57:40.348+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-15T18:33:52.721+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T18:33:52.727+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T18:33:52.727+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-15T18:33:52.735+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): update_transaction_fact> on 2023-12-14 00:00:00+00:00
[2023-12-15T18:33:52.739+0000] {standard_task_runner.py:57} INFO - Started process 126 to run task
[2023-12-15T18:33:52.741+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_transaction_fact', 'update_transaction_fact', 'scheduled__2023-12-14T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/transaction_fact.py', '--cfg-path', '/tmp/tmpiuua3dy6']
[2023-12-15T18:33:52.743+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask update_transaction_fact
[2023-12-15T18:33:52.780+0000] {task_command.py:416} INFO - Running <TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [running]> on host f4c0e6b5baef
[2023-12-15T18:33:52.844+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_transaction_fact' AIRFLOW_CTX_TASK_ID='update_transaction_fact' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-14T00:00:00+00:00'
[2023-12-15T18:33:52.848+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-15T18:33:52.859+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=daily_transaction_fact, task_id=update_transaction_fact, execution_date=20231214T000000, start_date=20231215T183352, end_date=20231215T183352
[2023-12-15T18:33:52.913+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-15T18:33:52.926+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-15T19:53:21.608+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T19:53:21.617+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T19:53:21.617+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-15T19:53:21.627+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): update_transaction_fact> on 2023-12-14 00:00:00+00:00
[2023-12-15T19:53:21.632+0000] {standard_task_runner.py:57} INFO - Started process 144 to run task
[2023-12-15T19:53:21.634+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_transaction_fact', 'update_transaction_fact', 'scheduled__2023-12-14T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/transaction_fact.py', '--cfg-path', '/tmp/tmpdxzzmgh9']
[2023-12-15T19:53:21.636+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask update_transaction_fact
[2023-12-15T19:53:21.673+0000] {task_command.py:416} INFO - Running <TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [running]> on host e1cf21a7c005
[2023-12-15T19:53:21.737+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_transaction_fact' AIRFLOW_CTX_TASK_ID='update_transaction_fact' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-14T00:00:00+00:00'
[2023-12-15T19:53:21.745+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-15T19:53:21.753+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=daily_transaction_fact, task_id=update_transaction_fact, execution_date=20231214T000000, start_date=20231215T195321, end_date=20231215T195321
[2023-12-15T19:53:21.806+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-15T19:53:21.820+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-15T20:59:40.259+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T20:59:40.266+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [queued]>
[2023-12-15T20:59:40.266+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-15T20:59:40.277+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): update_transaction_fact> on 2023-12-14 00:00:00+00:00
[2023-12-15T20:59:40.284+0000] {standard_task_runner.py:57} INFO - Started process 86 to run task
[2023-12-15T20:59:40.285+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_transaction_fact', 'update_transaction_fact', 'scheduled__2023-12-14T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/transaction_fact.py', '--cfg-path', '/tmp/tmp3m9_o3pd']
[2023-12-15T20:59:40.288+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask update_transaction_fact
[2023-12-15T20:59:40.327+0000] {task_command.py:416} INFO - Running <TaskInstance: daily_transaction_fact.update_transaction_fact scheduled__2023-12-14T00:00:00+00:00 [running]> on host 5df1e9d693e3
[2023-12-15T20:59:40.389+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_transaction_fact' AIRFLOW_CTX_TASK_ID='update_transaction_fact' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-14T00:00:00+00:00'
[2023-12-15T20:59:40.396+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-15T20:59:40.406+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=daily_transaction_fact, task_id=update_transaction_fact, execution_date=20231214T000000, start_date=20231215T205940, end_date=20231215T205940
[2023-12-15T20:59:40.458+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-15T20:59:40.485+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
